name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run on push event
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'umbrellio/sidekiq_web_google_auth'

    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0"]

    name: ${{ matrix.ruby }}

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake

      - uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest

    environment: Deploy

    # Run on push to master branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v1

      - uses: umbrellio/publish-ruby-gem-action@v1.0.4
        with:
          api-key: ${{ secrets.RUBYGEMS_API_KEY }}
        env:
          PUBLISH_JOB: true
